# Работа с NumPy

## Как работать с библиотекой NumPy

Загружаем библиотеку NumPy

In [1]:
import numpy as np


## Как создать одномерный массив и работать с ним

Создаем одномерный массив через фунцию array

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Запросим тип данны переменной a. Полусчим, что тип данных numpy array

In [5]:
type(a)

numpy.ndarray

Запросим количество элементов в массиве, применив функцию shape

In [6]:
a.shape

(5,)

Запросим размерность массива - ряд, применив функцию ndim. Он состоит из одного ряда.

In [8]:
a.ndim

1

Запросим информацию из каких типов данных состоит наш массив, применив фунцию dtype.

In [9]:
a.dtype

dtype('int64')

Создадим для примера массив

In [12]:
arr = [1,2,3,4,5,6,7,8,9]

In [13]:
a = np.array(arr)

In [14]:
a.dtype

dtype('int64')

Можем заменить тип данных при создании массива, ключив в него допополнительные параметры.

In [16]:
a = np.array(arr,dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Проверим тип данных элементов массива. У нас изменился тип данных с int64 перешел на float64

In [17]:
a.dtype

dtype('float64')

Можем изменить тип данных в массиве использовав оператор astype

In [20]:
a.astype(np.int32)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Применим арифметические действия. Для показательности используем массив b такого же размера, с теми же данными, но изменим 3 на 0.

In [22]:
b = np.array([1, 2, 0, 4, 5, 6, 7, 8, 9])

Сложение

In [23]:
a+b

array([ 2.,  4.,  3.,  8., 10., 12., 14., 16., 18.])

Вычитание

In [24]:
a-b

array([0., 0., 3., 0., 0., 0., 0., 0., 0.])

Умножение

In [ ]:
a*b

array([ 1.,  4.,  0., 16., 25., 36., 49., 64., 81.])

Деление. Обрати внимание - при делении на ноль показыавет не ошибку, а бесконечность.

In [26]:
a/b

C:\Users\MACHENIKE\AppData\Local\Temp\ipykernel_9448\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([ 1.,  1., inf,  1.,  1.,  1.,  1.,  1.,  1.])

Еще одни способ деления массивов

In [27]:
np.divide(a,b)

C:\Users\MACHENIKE\AppData\Local\Temp\ipykernel_9448\2626738034.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([ 1.,  1., inf,  1.,  1.,  1.,  1.,  1.,  1.])

Агрегация массива
1. Сумма.
2. Среднее
3. Минимум
4. Максимум

In [29]:
a.sum()

np.float64(45.0)

In [30]:
a.mean()

np.float64(5.0)

In [31]:
a.min()

np.float64(1.0)

In [32]:
a.max()

np.float64(9.0)

## Как создавать многомерный массив

Многомерный массив создается из нескольих списков, например список списков arr2 будет содержать две строки списков, получается, что это уже таблица

In [33]:
arr2=[[1,2,3,4,5],[1,2,3,4,5]]
arr2

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [38]:
b=np.array(arr2)
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [42]:
type(b)

numpy.ndarray

Запросим размер нашего массива, получим, что массив состоит из (2,5), где 2 количество срок, 5 количество элемнтов в сроке (столбцы)

In [40]:
b.shape

(2, 5)

In [43]:
b.ndim

2

Посмотрим, как будут работать массивы при аримфметических действия. Создадим массив c. Он будет такой же как b. Выполним сложение.

In [44]:
c=np.array(arr2)
c+b

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

Получили поэлементное сложение массивов. Сделаем деление. Матрицы разделились по элементно.

In [45]:
c/b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Посмотрим, что у нас с функциями агрегирования.

In [46]:
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

Суммируем по столбцам, для этого в функцию добавляем аргумент axis=0

In [47]:
b.sum(axis=0)

array([ 2,  4,  6,  8, 10])

Суммируем по срокам, для этого в функцию добавлям аргумент axis=1

In [48]:
b.sum(axis=1)

array([15, 15])

Создаем многомерную матрицу

In [49]:
arr3=[
    [
        [1,2,3,4,5],
        [1,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [1,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [1,2,3,4,5]
    ]
]

In [51]:
c=np.array(arr3, np.float32)
c

array([[[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]],

       [[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]],

       [[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]]], dtype=float32)

In [52]:
c.shape

(3, 2, 5)

In [54]:
c.sum(axis=0)

array([[ 3.,  6.,  9., 12., 15.],
       [ 3.,  6.,  9., 12., 15.]], dtype=float32)

In [55]:
c.sum(axis=1)

array([[ 2.,  4.,  6.,  8., 10.],
       [ 2.,  4.,  6.,  8., 10.],
       [ 2.,  4.,  6.,  8., 10.]], dtype=float32)

In [57]:
c.sum(axis=2)

array([[15., 15.],
       [15., 15.],
       [15., 15.]], dtype=float32)

## Как работать с многомерным массивом

Повторим и углубим предыщеий вариант, для наглядности изменим наш массив.

In [25]:
arr4=[
    [
        [1,2,3,4,5],
        [8,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [115,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [1024,2,3,4,5]
    ]
]

In [26]:
c=np.array(arr4, np.int64)
c

array([[[   1,    2,    3,    4,    5],
        [   8,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [ 115,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [1024,    2,    3,    4,    5]]])

Начинаем работь с функцией суммирования.
1. Суммирование по всем осям - суммируются все элементы матрицы (массива).
2. Суммирование по оси X.
3. Суммирование по оси Y.
4. Суммирование по оси Z.

In [61]:
c.sum()

np.int64(1234)

In [62]:
c.sum(axis=0)

array([[   3,    6,    9,   12,   15],
       [1147,    6,    9,   12,   15]])

In [63]:
c.sum(axis=1)

array([[   9,    4,    6,    8,   10],
       [ 116,    4,    6,    8,   10],
       [1025,    4,    6,    8,   10]])

In [64]:
c.sum(axis=2)

array([[  15,   22],
       [  15,  129],
       [  15, 1038]])

Но мы можем пойти дальше и указать в параметре axis кортеж из нескольких осей.

In [65]:
c.sum(axis=(0,1))

array([1150,   12,   18,   24,   30])

Что будет если сложить два массива с разными рядами?

In [4]:
f=np.array([[1,2,3],[1,2,3]])
f

array([[1, 2, 3],
       [1, 2, 3]])

In [70]:
e=np.array([1,2,3])
e

array([1, 2, 3])

Сложение с одномерным массивом выполняется корректно, оба ряда первого массива суммируются с одним рядом второго массива.

In [71]:
f+e

array([[2, 4, 6],
       [2, 4, 6]])

Сложение с многомерным массивом, с количеством рядов больше одного уже не работает, получаем ошибку

In [2]:
s=np.array([[1,2,3],[1,2,3],[1,2,3]])
s

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
f+s

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

## Как создать стандартизированные многомерные массивы

Функция создаем готовые массивы.
1. Функция eye - создает массив, указываем его размер, особенность, все заполнено нулями, кроме центральной диагонали - там только единицы.
2. Функция zeros - создает массив, особенность - указываем его размер в виде кортежа (дополнительные скобки), все данные заполнены нулями.
3. Функция empty - создает массив, особенность - указываем его размер в виде кортежа (дополнительные скобки), все данные чем то ??? Очень осторожное использование.
4. Функция fill - создает массив, особенность - указыаем его размер в виде кортежа(дополнительные скобки), в качестве заполнления указыаем value.
5. Функция ones - создаем массив, особенность все заполнено единицами.
6. Фунция ones_like() - создает массив заполненный единцами, особенность в скобках нужно указать массив, в качестве примера, из его размера будет создан аналогичный массив заполенный единицами.

In [6]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.empty((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [13]:
np.full((2,2,2), fill_value=15)

array([[[15, 15],
        [15, 15]],

       [[15, 15],
        [15, 15]]])

In [16]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## Как работать с многомерным массивом

Если стоит задача, получить значения из числового ряда с одинаковыми диапозоном, в numpy это решается через функцию arange. Указываем начало диапозона, конец диапозона и шаг, с которым нужно выполнить ряд.

In [18]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

Если стоит задача разбить диапозон на определенное количество точек, тогда лучше использовать функцию linspace. Указаываем начало диапозона, конец диапозона и количество точек, формируется массив с разбивкой по точкам.

In [22]:
np.linspace (0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

## Как индексировать массивы и формировать срезы

Учимся получать данные из матрицы. Вызовем массив c из предыдущих примеров. Посмотрим ее размер.


In [28]:
c

array([[[   1,    2,    3,    4,    5],
        [   8,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [ 115,    2,    3,    4,    5]],

       [[   1,    2,    3,    4,    5],
        [1024,    2,    3,    4,    5]]])

In [29]:
c.shape

(3, 2, 5)

Если будем вызывать поочередно ее ряды, получим одномерные массивы.

In [32]:
c[0]

array([[1, 2, 3, 4, 5],
       [8, 2, 3, 4, 5]])

In [33]:
c[1]

array([[  1,   2,   3,   4,   5],
       [115,   2,   3,   4,   5]])

In [34]:
c[2]

array([[   1,    2,    3,    4,    5],
       [1024,    2,    3,    4,    5]])

Но мы можем выбрать из конкретной матрицы конкретную стороку, например выбираем из второй матрицы вторую сроку.

In [35]:
c[1,1]

array([115,   2,   3,   4,   5])

А если мы хотим из нее выбрать конкретный элемент, наример первый - записываем так:

In [36]:
c[1,1,0]

np.int64(115)

Если мы хотим выбрать определенный диапозон со второй по третью матрицу, со второй по последующую строку, до третьего элемента, то записываем:

In [37]:
c[1:,1:,:2]

array([[[ 115,    2]],

       [[1024,    2]]])

Если нам нужно указать диапозон в ряду, тогда запишем так:
Для наглядности сначала вытащим целый ряд из массива

In [40]:
c[2,1]

array([1024,    2,    3,    4,    5])

А теперь вытащим из ряда элементы с первого по четвертый (помним, что счет начинается с 0, последний элемент, который указан - не берется)

In [ ]:
c[2,1,::-1]

array([2, 3, 4])

Если мы хотим перевенуть ряд используем ::-1

In [43]:
c[2,1,::-1]

array([   5,    4,    3,    2, 1024])

Если мы хотим взять из ряда через второй элемент, тогда используем ::2

In [44]:
c[2,1,::2]

array([1024,    3,    5])

Можем усложнить и взять элементы из диапозона

In [49]:
c[2,1,1:4:2]

array([2, 4])

Кроме того, если мы хотим изменить эти элементы мы испозуем следующее:

In [50]:
c[2,1,1:4:2]=100

Элементы поменяли значение.

In [51]:
c[2,1]

array([1024,  100,    3,  100,    5])

Еще один интересный момент создадим массив a

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

Сделаем другой массив b равный a

In [3]:
b=a
b

array([1, 2, 3, 4, 5])

Теперь заменим в массиве b второй элемент и снова сравним эти массивы

In [4]:
b[1]=1000
print(a,b)

[   1 1000    3    4    5] [   1 1000    3    4    5]


Как мы видим поменялись оба массива. Чтобы это не происходило нужно использовать функцию copy

In [5]:
c=a.copy()
print (c,a)
c[0]=500000
print(c,a)

[   1 1000    3    4    5] [   1 1000    3    4    5]
[500000   1000      3      4      5] [   1 1000    3    4    5]


## Что такое бродкастинг

Для общего понимания бродкастинга используем пример. Имеем массив из трех чисел. Умножаем его на какое то число, получаем новый массив, где каждый элемент предыщего массива перемножен на указанное число.

In [2]:
a=np.array([1,2,3], np.int32)
print(a)
x=5
b=a*x
print(b)

[1 2 3]
[ 5 10 15]


Нам кажется, что каждый элемент массива был умножен на одно и тоже число, на самом деле "по капотом" по числу  x был создан массив [5,5,5], элементы которого были премножены на первый массив т.е. a=[1,2,3]*x=5=>x=[5,5,5]=[5,10,15]

Усложним задачу, возмем два многомерных массив. Создадим их используя функцию ones и вытащим их размер.

In [21]:
x=np.ones((2,1,5,8))
y=np.ones((2,8,5,1))
x.shape, y.shape

((2, 1, 5, 8), (2, 8, 5, 1))

Теперь создадим новый массив перемножив значения из двух предыдущих массивов и вытащим их размер. Мы видим, что размер в сводной матрице поменялся, из двух матриц были взяты наибольшие значение векторов. Но это работает только если один из векторов равен единице, в противном случае бродкастинг работать не будет

In [22]:
z= x*y
z.shape

(2, 8, 5, 8)

In [23]:
x=np.ones((2,2,5,8))
y=np.ones((2,8,5,5))
print(x.shape, y.shape)
z= x*y
print(z.shape)

(2, 2, 5, 8) (2, 8, 5, 5)


ValueError: operands could not be broadcast together with shapes (2,2,5,8) (2,8,5,5) 

Мы видим, что в этом случае бродкастинг не сработал.

## Как изменить форму массивов. Часть 1